[book]
authors = ["chenxizhan"]
language = "en"
multilingual = false
src = "src"
title = "note-git"

[output.html]
git-repository-url = "https://github.com/chenxizhan1995/note-git.git"

[output.html.fold]
enable = true
level = 0
